<?php
// migrate-remaining-responses.php
//
// Generic version of migrate-guided-practice-1-5-responses.php, driven by
// a subContentId->fieldid mapping JSON (generated by the same Python code
// path that assigned e1/e2/.../m1/m2/... ids in the rebuilt HTML page, so
// ids are guaranteed to line up -- not hand-transcribed for the 48 total
// essay items across these 3 activities).
//
// Migrates: 1.6 Independent Practice (h5pactivityid=89 -> new cmid=278),
// Lesson 2 Independent Practice (91 -> 279), Lesson 2 Guided Practice
// (92 -> 280). Takes the most recent response per (userid, subcontent).
//
// Run: sudo -u www-data php migrate-remaining-responses.php

define('CLI_SCRIPT', true);
require('/var/www/moodle/config.php');

\core\cron::setup_user();

$newcourseid = 5;
$MAPDIR = '/tmp/foxcs-deploy-stage/seminar3-mappings';

$JOBS = [
    ['h5pactivityid' => 89, 'newcmid' => 278, 'mapfile' => "$MAPDIR/mapping_211.json", 'label' => '1.6 Independent Practice'],
    ['h5pactivityid' => 91, 'newcmid' => 279, 'mapfile' => "$MAPDIR/mapping_256.json", 'label' => 'Lesson 2 Independent Practice'],
    ['h5pactivityid' => 92, 'newcmid' => 280, 'mapfile' => "$MAPDIR/mapping_257.json", 'label' => 'Lesson 2 Guided Practice'],
];

foreach ($JOBS as $job) {
    $map = json_decode(file_get_contents($job['mapfile']), true);
    $essaymap = array_flip($map['essay']); // subcontent -> fieldid
    $mcmap = array_flip($map['mc']);
    $allsubcontent = array_merge(array_keys($essaymap), array_keys($mcmap));

    list($insql, $params) = $DB->get_in_or_equal($allsubcontent, SQL_PARAMS_NAMED);
    $rows = $DB->get_records_sql("
        SELECT ar.id, at.userid, ar.subcontent, ar.response, ar.timecreated
          FROM {h5pactivity_attempts_results} ar
          JOIN {h5pactivity_attempts} at ON at.id = ar.attemptid
         WHERE at.h5pactivityid = :h5pactivityid
           AND ar.subcontent $insql
         ORDER BY at.userid, ar.timecreated DESC
    ", array_merge(['h5pactivityid' => $job['h5pactivityid']], $params));

    $latest = [];
    foreach ($rows as $row) {
        $key = $row->userid . '|' . $row->subcontent;
        if (!isset($latest[$key])) {
            $latest[$key] = $row;
        }
    }

    $byuser = [];
    foreach ($latest as $row) {
        $byuser[$row->userid] = $byuser[$row->userid] ?? ['essay' => [], 'mc' => []];
        if (isset($essaymap[$row->subcontent])) {
            $byuser[$row->userid]['essay'][$essaymap[$row->subcontent]] = $row->response;
        } elseif (isset($mcmap[$row->subcontent])) {
            $byuser[$row->userid]['mc'][$mcmap[$row->subcontent]] = $row->response;
        }
    }

    $migrated = 0;
    foreach ($byuser as $userid => $state) {
        $record = new stdClass();
        $record->userid = $userid;
        $record->courseid = $newcourseid;
        $record->cmid = $job['newcmid'];
        $record->eventtype = 'progress_state';
        $record->payload = json_encode($state);
        $record->timecreated = time();
        $DB->insert_record('local_foxcstelemetry_log', $record);
        $migrated++;
    }

    echo "{$job['label']} (cmid={$job['newcmid']}): migrated {$migrated} students.\n";

    $allolduserids = $DB->get_fieldset_sql(
        "SELECT DISTINCT at.userid FROM {h5pactivity_attempts} at WHERE at.h5pactivityid = ?",
        [$job['h5pactivityid']]
    );
    $notmigrated = array_diff($allolduserids, array_keys($byuser));
    if ($notmigrated) {
        echo "  NOT migrated (no data under current-generation subContentIds): " . implode(', ', $notmigrated) . "\n";
    }
}

echo "Done.\n";
