<?php
// rebuild-remaining-essay-pages.php
//
// Same fix as rebuild-lesson1-guided-practice.php (cmid=210 -> 277,
// already deployed), applied to the remaining 3 activities with the same
// H5P.Essay `enableRetry:false` lock bug: 1.6 Independent Practice
// (cmid=211), Lesson 2 Independent Practice (cmid=256), Lesson 2 Guided
// Practice (cmid=257). Source HTML generated by
// generate_seminar3_practice_page.py from each activity's real extracted
// content.json -- see that script and courses/seminar-iii/content/lesson-
// {1,2}/{guided,independent}-practice/ for the generated files.
//
// Run: sudo -u www-data php rebuild-remaining-essay-pages.php

define('CLI_SCRIPT', true);
require('/var/www/moodle/config.php');
require_once($CFG->dirroot . '/course/lib.php');
require_once($CFG->dirroot . '/course/modlib.php');
require_once($CFG->dirroot . '/lib/resourcelib.php');
require_once($CFG->dirroot . '/mod/resource/locallib.php');

\core\cron::setup_user();

$courseid = 5; // foxcs-seminar3
$fs = get_file_storage();
$usercontext = context_user::instance($USER->id);

$ACTIVITIES = [
    [
        'oldcmid' => 211,
        'oldh5pactivityid' => 89,
        'expectedname' => '1.6 -- Independent Practice',
        'newname' => '1.6 -- Independent Practice',
        'newidnumber' => 'seminar3-lesson1-independent-practice-v2',
        'sectionnum' => 2,
        'beforemod' => 42,
        'sourcefile' => '/tmp/foxcs-deploy-stage/seminar3-remaining/lesson-1-independent-practice.html',
    ],
    [
        'oldcmid' => 256,
        'oldh5pactivityid' => 91,
        'expectedname' => 'Lesson 2 Independent Practice',
        'newname' => 'Lesson 2 Independent Practice',
        'newidnumber' => 'seminar3-lesson2-independent-practice-v2',
        'sectionnum' => 3,
        'beforemod' => 257,
        'sourcefile' => '/tmp/foxcs-deploy-stage/seminar3-remaining/lesson-2-independent-practice.html',
    ],
    [
        'oldcmid' => 257,
        'oldh5pactivityid' => 92,
        'expectedname' => 'Lesson 2 Guided Practice',
        'newname' => 'Lesson 2 Guided Practice',
        'newidnumber' => 'seminar3-lesson2-guided-practice-v2',
        'sectionnum' => 3,
        'beforemod' => null, // append at end -- 257 is currently last in its section.
        'sourcefile' => '/tmp/foxcs-deploy-stage/seminar3-remaining/lesson-2-guided-practice.html',
    ],
];

foreach ($ACTIVITIES as $cfg) {
    $oldh5p = $DB->get_record('h5pactivity', ['id' => $cfg['oldh5pactivityid']], '*', MUST_EXIST);
    if ($oldh5p->name !== $cfg['expectedname']) {
        fwrite(STDERR, "Unexpected h5pactivity name for id={$cfg['oldh5pactivityid']}: {$oldh5p->name}\n");
        exit(1);
    }

    $existing = $DB->get_record('course_modules', ['course' => $courseid, 'idnumber' => $cfg['newidnumber']]);
    if ($existing) {
        echo "{$cfg['newidnumber']}: already exists as cmid={$existing->id}, skipped.\n";
        continue;
    }

    $html = file_get_contents($cfg['sourcefile']);
    if ($html === false) {
        fwrite(STDERR, "Could not read {$cfg['sourcefile']}\n");
        exit(1);
    }

    $draftitemid = file_get_unused_draft_itemid();
    $fs->create_file_from_string([
        'contextid' => $usercontext->id,
        'component' => 'user',
        'filearea' => 'draft',
        'itemid' => $draftitemid,
        'filepath' => '/',
        'filename' => 'index.html',
    ], '<html><body>placeholder</body></html>');

    $moduleinfo = new stdClass();
    $moduleinfo->modulename = 'resource';
    $moduleinfo->module = $DB->get_field('modules', 'id', ['name' => 'resource']);
    $moduleinfo->course = $courseid;
    $moduleinfo->section = $cfg['sectionnum'];
    $moduleinfo->visible = 1;
    $moduleinfo->name = $cfg['newname'];
    $moduleinfo->idnumber = $cfg['newidnumber'];
    $moduleinfo->introeditor = ['text' => '', 'format' => FORMAT_HTML, 'itemid' => 0];
    $moduleinfo->files = $draftitemid;
    $moduleinfo->display = RESOURCELIB_DISPLAY_EMBED;
    $moduleinfo->completion = COMPLETION_TRACKING_MANUAL;
    if ($cfg['beforemod']) {
        $moduleinfo->beforemod = $cfg['beforemod'];
    }

    $result = create_module($moduleinfo);
    $newcmid = $result->coursemodule;
    $modcontext = context_module::instance($newcmid);
    $fs->delete_area_files($modcontext->id, 'mod_resource', 'content', 0);

    $finalhtml = str_replace('__CMID__', (string) $newcmid, $html);
    $fs->create_file_from_string([
        'contextid' => $modcontext->id,
        'component' => 'mod_resource',
        'filearea' => 'content',
        'itemid' => 0,
        'filepath' => '/',
        'filename' => 'index.html',
    ], $finalhtml);
    file_set_sortorder($modcontext->id, 'mod_resource', 'content', 0, '/', 'index.html', 1);

    $DB->set_field('course_modules', 'visible', 0, ['id' => $cfg['oldcmid']]);
    set_coursemodule_visible($cfg['oldcmid'], 0);

    echo "{$cfg['newname']}: new cmid={$newcmid}, old cmid={$cfg['oldcmid']} hidden.\n";
}

rebuild_course_cache($courseid, true);
echo "Done.\n";
