# ACT Math Baseline -- Lesson 1, Seminar III
# 24 questions, matching lesson-1-plan sections 22-25 (domain/difficulty distribution).
# Each entry also carries baseline-only metadata (id, domain, skill, difficulty,
# expected_strategy, misconception, error_type) used to build the teacher-only
# metadata/skill-map doc -- not included in the H5P package itself.

QUESTIONS = [
    dict(id="B01", domain="Numbers & Operations", skill="Order of operations", difficulty="A",
         strategy="Apply multiplication before addition/subtraction, left to right",
         misconception="Left-to-right without operation precedence", error_type="Process",
         question="<p>Evaluate: 9 &minus; 2 &times; 3 + 4</p>",
         answers=[
             ("<div>3</div>", False, "<div>This drops the final + 4 step. Try: after finding 9 &minus; 6, add the 4.</div>"),
             ("<div>25</div>", False, "<div>This solves left to right instead of doing the multiplication first. Try: 2 &times; 3 first.</div>"),
             ("<div>7</div>", True, "<div>2 &times; 3 = 6, then 9 &minus; 6 + 4 = 7.</div>"),
             ("<div>&minus;5</div>", False, "<div>This adds 3 and 4 before multiplying, which changes the problem. Try: only 2 &times; 3 gets grouped.</div>"),
         ]),
    dict(id="B02", domain="Numbers & Operations", skill="Adding/subtracting signed numbers", difficulty="A",
         strategy="Rewrite subtracting a negative as adding a positive",
         misconception="Double negative not flipped to addition", error_type="Process",
         question="<p>Evaluate: &minus;8 + 5 &minus; (&minus;3)</p>",
         answers=[
             ("<div>&minus;6</div>", False, "<div>Subtracting a negative 3 should become adding 3. Try: rewrite &minus;(&minus;3) as +3.</div>"),
             ("<div>0</div>", True, "<div>&minus;8 + 5 + 3 = 0.</div>"),
             ("<div>&minus;16</div>", False, "<div>This treats every number as negative. Try: only the middle term is positive (+5).</div>"),
             ("<div>10</div>", False, "<div>This drops the negative sign on the first number. Try: start at &minus;8, not 8.</div>"),
         ]),
    dict(id="B03", domain="Numbers & Operations", skill="Signed numbers in context", difficulty="B",
         strategy="Track direction (up/down) as positive/negative and combine in order",
         misconception="Treats a descent as addition instead of subtraction", error_type="Comprehension",
         question="<p>A submarine is at 120 feet below sea level. It rises 45 feet, then descends 60 feet. What is its new depth?</p>",
         answers=[
             ("<div>75 feet below sea level</div>", False, "<div>This stops after the rise and skips the descent. Try: apply both moves in order.</div>"),
             ("<div>135 feet below sea level</div>", True, "<div>&minus;120 + 45 &minus; 60 = &minus;135, so 135 feet below sea level.</div>"),
             ("<div>225 feet below sea level</div>", False, "<div>This treats the 45-foot rise as a drop instead of an increase. Try: rising means adding, not subtracting.</div>"),
             ("<div>105 feet above sea level</div>", False, "<div>This mixes up the direction of the starting depth. Try: 120 feet below sea level starts as &minus;120.</div>"),
         ]),
    dict(id="B04", domain="Numbers & Operations", skill="Estimation", difficulty="C",
         strategy="Round to a friendly number, then multiply",
         misconception="Uses only one end of a range instead of a reasonable middle value", error_type="Strategy",
         question="<p>A reaction produces between 2.8 and 3.4 grams of product per trial, run over 12 trials. Which is the best estimate of the total grams produced?</p>",
         answers=[
             ("<div>about 34 g</div>", False, "<div>This only uses the lowest possible amount per trial. Try: use a reasonable middle value, like 3 g.</div>"),
             ("<div>about 36 g</div>", True, "<div>Rounding to about 3 g per trial: 3 &times; 12 = 36 g.</div>"),
             ("<div>about 41 g</div>", False, "<div>This only uses the highest possible amount per trial. Try: a middle estimate is more reasonable than the maximum.</div>"),
             ("<div>about 7 g</div>", False, "<div>This estimates the range itself instead of the total. Try: multiply grams-per-trial by the number of trials.</div>"),
         ]),
    dict(id="B05", domain="Fractions & Decimals", skill="Fraction-to-decimal conversion", difficulty="A",
         strategy="Divide the numerator by the denominator",
         misconception="Flips numerator and denominator", error_type="Comprehension",
         question="<p>Write 3/8 as a decimal.</p>",
         answers=[
             ("<div>0.35</div>", False, "<div>Check the division again: 3 &divide; 8, not a rounded guess.</div>"),
             ("<div>0.375</div>", True, "<div>3 &divide; 8 = 0.375.</div>"),
             ("<div>0.38</div>", False, "<div>Close, but this rounds too early. Try: 3 &divide; 8 all the way out.</div>"),
             ("<div>2.67</div>", False, "<div>This divides 8 by 3 instead of 3 by 8. Try: numerator &divide; denominator, in that order.</div>"),
         ]),
    dict(id="B06", domain="Fractions & Decimals", skill="Adding fractions, unlike denominators", difficulty="B",
         strategy="Find a common denominator before adding",
         misconception="Adds numerators and denominators straight across", error_type="Process",
         question="<p>Compute: 2/3 + 1/4</p>",
         answers=[
             ("<div>3/7</div>", False, "<div>This adds numerators and denominators separately. Try: find a common denominator first.</div>"),
             ("<div>11/12</div>", True, "<div>2/3 = 8/12 and 1/4 = 3/12, so 8/12 + 3/12 = 11/12.</div>"),
             ("<div>11/7</div>", False, "<div>The numerator is right, but the denominator wasn't converted to a common denominator. Try: both fractions need the same bottom number.</div>"),
             ("<div>3/4</div>", False, "<div>Check the common denominator step again &mdash; 3/12 shouldn't simplify away like that.</div>"),
         ]),
    dict(id="B07", domain="Fractions & Decimals", skill="Dividing fractions", difficulty="B",
         strategy="Multiply by the reciprocal of the second fraction",
         misconception="Multiplies straight across without taking the reciprocal", error_type="Process",
         question="<p>Compute: 3/5 &divide; 2/3</p>",
         answers=[
             ("<div>2/5</div>", False, "<div>This multiplies the fractions as given. Try: flip the second fraction first, then multiply.</div>"),
             ("<div>9/10</div>", True, "<div>3/5 &divide; 2/3 = 3/5 &times; 3/2 = 9/10.</div>"),
             ("<div>10/9</div>", False, "<div>This flips the first fraction instead of the second. Try: keep the first fraction as is, flip the one after the &divide; sign.</div>"),
             ("<div>3/10</div>", False, "<div>Check which numbers get multiplied together after flipping the second fraction.</div>"),
         ]),
    dict(id="B08", domain="Fractions & Decimals", skill="Fraction word problem, multi-step", difficulty="C",
         strategy="Convert the mixed number, then multiply by the fractional part of a batch",
         misconception="Divides instead of multiplies, or ignores the whole-number part", error_type="Strategy",
         question="<p>A recipe needs 2&frac14; cups of flour for one batch. A baker wants to make 1/3 of a batch. How many cups of flour are needed?</p>",
         answers=[
             ("<div>3/4 cup</div>", True, "<div>2&frac14; = 9/4. 9/4 &times; 1/3 = 9/12 = 3/4 cup.</div>"),
             ("<div>2/3 cup</div>", False, "<div>This only scales the whole-number part of 2&frac14;. Try: convert the full mixed number to a fraction first.</div>"),
             ("<div>6&frac34; cups</div>", False, "<div>This divides by 1/3 instead of multiplying. Try: making a smaller portion means multiplying by a fraction less than 1.</div>"),
             ("<div>2 7/12 cups</div>", False, "<div>This adds the fractions instead of multiplying. Try: a portion of a recipe is found by multiplying.</div>"),
         ]),
    dict(id="B09", domain="Percent", skill="Percent of a number", difficulty="A",
         strategy="Convert the percent to a decimal, then multiply",
         misconception="Finds 10% and forgets to scale up (or down) to the target percent", error_type="Process",
         question="<p>What is 30% of 150?</p>",
         answers=[
             ("<div>15</div>", False, "<div>This finds 10% of 150 and stops. Try: 30% is three times that.</div>"),
             ("<div>45</div>", True, "<div>0.30 &times; 150 = 45.</div>"),
             ("<div>120</div>", False, "<div>This subtracts 30 from 150 instead of finding 30% of 150.</div>"),
             ("<div>4.5</div>", False, "<div>The decimal point is in the wrong place. Try: 30% = 0.30, not 0.03.</div>"),
         ]),
    dict(id="B10", domain="Percent", skill="Percent increase", difficulty="B",
         strategy="Divide the amount of change by the original amount",
         misconception="Uses the new (final) amount as the base instead of the original", error_type="Comprehension",
         question="<p>A shirt's price increased from $40 to $46. What was the percent increase?</p>",
         answers=[
             ("<div>6%</div>", False, "<div>This treats the $6 change itself as the percent. Try: divide the change by the original price.</div>"),
             ("<div>13%</div>", False, "<div>This divides the change by the new price ($46) instead of the original price. Try: percent increase compares to where you started.</div>"),
             ("<div>15%</div>", True, "<div>Change = $6. 6 &divide; 40 = 0.15 = 15%.</div>"),
             ("<div>115%</div>", False, "<div>This finds the new price as a percent of the old price but forgets to subtract the original 100%.</div>"),
         ]),
    dict(id="B11", domain="Percent", skill="Multi-step percent (discount + tax)", difficulty="C",
         strategy="Apply the discount first, then apply tax to the discounted price",
         misconception="Combines the two percents into one instead of applying them in sequence", error_type="Strategy",
         question="<p>A jacket costs $60. It is discounted 20%, and then a 5% sales tax is applied to the discounted price. What is the final price?</p>",
         answers=[
             ("<div>$48.00</div>", False, "<div>This applies the discount correctly but forgets the tax step. Try: apply 5% tax to the new $48 price.</div>"),
             ("<div>$48.60</div>", False, "<div>This applies the tax to the discount amount instead of the discounted price.</div>"),
             ("<div>$50.40</div>", True, "<div>$60 &times; 0.80 = $48. $48 &times; 1.05 = $50.40.</div>"),
             ("<div>$51.00</div>", False, "<div>This combines 20% off and 5% tax into a single 15%-off calculation. Try: apply each percent as its own step.</div>"),
         ]),
    dict(id="B12", domain="Ratios, Rates & Proportions", skill="Unit rate", difficulty="A",
         strategy="Divide distance by time",
         misconception="Divides in the wrong direction", error_type="Process",
         question="<p>A car travels 240 miles in 4 hours. What is its rate in miles per hour?</p>",
         answers=[
             ("<div>40 mph</div>", False, "<div>Check the division again: 240 &divide; 4.</div>"),
             ("<div>60 mph</div>", True, "<div>240 &divide; 4 = 60 miles per hour.</div>"),
             ("<div>244 mph</div>", False, "<div>This adds instead of dividing. Try: rate is distance &divide; time.</div>"),
             ("<div>960 mph</div>", False, "<div>This multiplies instead of dividing. Try: rate is distance &divide; time.</div>"),
         ]),
    dict(id="B13", domain="Ratios, Rates & Proportions", skill="Solving a proportion", difficulty="B",
         strategy="Cross multiply, then divide",
         misconception="Inverts the proportion before solving", error_type="Process",
         question="<p>Solve for x: 3/8 = x/40</p>",
         answers=[
             ("<div>13.3</div>", False, "<div>This solves 40/3 instead of setting up the cross-product correctly.</div>"),
             ("<div>15</div>", True, "<div>Cross multiply: 8x = 3 &times; 40 = 120, so x = 15.</div>"),
             ("<div>106.7</div>", False, "<div>The cross-multiplication paired the wrong numbers. Try: multiply straight across the equals sign (3 &times; 40 and 8 &times; x).</div>"),
             ("<div>32</div>", False, "<div>This subtracts instead of solving the proportion. Try: cross multiply first.</div>"),
         ]),
    dict(id="B14", domain="Ratios, Rates & Proportions", skill="Ratio word problem, scaling", difficulty="C",
         strategy="Set up a proportion using the given ratio, then solve for the unknown",
         misconception="Uses the ratio flipped (water-to-rice instead of rice-to-water)", error_type="Comprehension",
         question="<p>A recipe uses a ratio of 2 cups of rice to 3 cups of water. A cook wants to make a large batch using 9 cups of water. How many cups of rice are needed?</p>",
         answers=[
             ("<div>4.5 cups</div>", False, "<div>This just halves 9 instead of using the 2:3 ratio. Try: set up 2/3 = x/9.</div>"),
             ("<div>6 cups</div>", True, "<div>2/3 = x/9. Cross multiply: 3x = 18, so x = 6.</div>"),
             ("<div>11 cups</div>", False, "<div>This adds instead of scaling the ratio. Try: use a proportion, not addition.</div>"),
             ("<div>13.5 cups</div>", False, "<div>This uses the ratio flipped (water to rice instead of rice to water).</div>"),
         ]),
    dict(id="B15", domain="Variables & Expressions", skill="Evaluating an expression", difficulty="A",
         strategy="Substitute the value, then follow order of operations",
         misconception="Groups the subtraction with the variable before multiplying", error_type="Process",
         question="<p>Evaluate 4x &minus; 7 when x = 5.</p>",
         answers=[
             ("<div>&minus;8</div>", False, "<div>This computes 4(5 &minus; 7) instead of (4 &times; 5) &minus; 7. Try: multiply first, then subtract.</div>"),
             ("<div>2</div>", False, "<div>This adds 4 and 5 instead of multiplying. Try: 4x means 4 &times; x.</div>"),
             ("<div>13</div>", True, "<div>4(5) = 20, then 20 &minus; 7 = 13.</div>"),
             ("<div>27</div>", False, "<div>The sign on 7 flipped. Try: the expression subtracts 7, it doesn't add it.</div>"),
         ]),
    dict(id="B16", domain="Variables & Expressions", skill="Combining like terms", difficulty="B",
         strategy="Group and combine the x-terms, then the constant terms",
         misconception="Adds coefficients that should be subtracted, or the reverse", error_type="Process",
         question="<p>Simplify: 5x + 3 &minus; 2x + 8</p>",
         answers=[
             ("<div>3x + 11</div>", True, "<div>5x &minus; 2x = 3x. 3 + 8 = 11.</div>"),
             ("<div>7x + 11</div>", False, "<div>This adds the x-coefficients instead of subtracting. Try: 5x &minus; 2x, not 5x + 2x.</div>"),
             ("<div>3x &minus; 5</div>", False, "<div>The sign on the constants flipped. Try: 3 + 8, not 3 &minus; 8.</div>"),
             ("<div>3x + 5</div>", False, "<div>Check the constant terms again: 3 and 8 should be added, not subtracted.</div>"),
         ]),
    dict(id="B17", domain="Variables & Expressions", skill="Translating words to an expression", difficulty="B",
         strategy="Identify the quantity being reduced and write the subtraction in the correct order",
         misconception="Reverses the order in a 'less than' phrase", error_type="Comprehension",
         question="<p>Write an expression for &quot;7 less than three times a number n.&quot;</p>",
         answers=[
             ("<div>3n &minus; 7</div>", True, "<div>&quot;7 less than&quot; means subtract 7 from three times n.</div>"),
             ("<div>7 &minus; 3n</div>", False, "<div>&quot;7 less than X&quot; means X &minus; 7, not 7 &minus; X. Try: rewrite as &quot;three times n, minus 7.&quot;</div>"),
             ("<div>3(n &minus; 7)</div>", False, "<div>This groups the subtraction with n itself. Try: only 7 is being subtracted, not 7 from n first.</div>"),
             ("<div>3n + 7</div>", False, "<div>&quot;Less than&quot; means subtraction, not addition.</div>"),
         ]),
    dict(id="B18", domain="Equations", skill="Two-step equation", difficulty="A",
         strategy="Undo addition/subtraction first, then undo multiplication/division",
         misconception="Divides before subtracting, or vice versa, in the wrong order", error_type="Process",
         question="<p>Solve for x: 2x + 5 = 17</p>",
         answers=[
             ("<div>6</div>", True, "<div>2x = 12, so x = 6.</div>"),
             ("<div>8.5</div>", False, "<div>This divides by 2 before subtracting the 5. Try: subtract 5 first, then divide.</div>"),
             ("<div>11</div>", False, "<div>This adds 5 instead of subtracting it. Try: undo the +5 by subtracting.</div>"),
             ("<div>24</div>", False, "<div>This multiplies instead of dividing at the last step.</div>"),
         ]),
    dict(id="B19", domain="Equations", skill="Multi-step equation with distribution", difficulty="B",
         strategy="Distribute first, then isolate the variable",
         misconception="Forgets to distribute across both terms in the parentheses", error_type="Process",
         question="<p>Solve for x: 3(x &minus; 4) = 18</p>",
         answers=[
             ("<div>2</div>", False, "<div>The sign flipped during distribution. Try: 3 times &minus;4 is &minus;12, not +12.</div>"),
             ("<div>7.3</div>", False, "<div>This only distributes to the x, not the 4. Try: 3(x &minus; 4) = 3x &minus; 12.</div>"),
             ("<div>10</div>", True, "<div>3x &minus; 12 = 18, so 3x = 30, and x = 10.</div>"),
             ("<div>30</div>", False, "<div>This finds 3x but forgets the final division by 3.</div>"),
         ]),
    dict(id="B20", domain="Equations", skill="Equation word problem (perimeter)", difficulty="C",
         strategy="Write an expression for each side, then set up the perimeter equation",
         misconception="Forgets a term when writing the expression, or solves for the wrong quantity", error_type="Comprehension",
         question="<p>A rectangle's length is 3 more than twice its width. If the perimeter is 36, what is the width?</p>",
         answers=[
             ("<div>5</div>", True, "<div>Let w = width, length = 2w + 3. Perimeter: 2(2w + 3 + w) = 6w + 6 = 36, so w = 5.</div>"),
             ("<div>6</div>", False, "<div>This ignores the &quot;+3&quot; in the length. Try: length = 2w + 3, not just 2w.</div>"),
             ("<div>11</div>", False, "<div>This sets up length + width = 36 instead of doubling for perimeter.</div>"),
             ("<div>13</div>", False, "<div>This finds the length, not the width the question asked for.</div>"),
         ]),
    dict(id="B21", domain="Mixed Application", skill="Linear cost model", difficulty="B",
         strategy="Subtract the fixed fee, then divide by the per-unit rate",
         misconception="Divides the total bill by the rate without subtracting the fixed fee", error_type="Process",
         question="<p>A phone plan costs $25 per month plus $0.10 per text message sent. If a customer's bill was $37, how many text messages did they send?</p>",
         answers=[
             ("<div>12</div>", False, "<div>This is the dollar amount above the base fee, not the number of texts. Try: divide that amount by $0.10.</div>"),
             ("<div>120</div>", True, "<div>$37 &minus; $25 = $12. $12 &divide; $0.10 = 120 texts.</div>"),
             ("<div>250</div>", False, "<div>This divides the base fee by the rate instead of the amount above it.</div>"),
             ("<div>370</div>", False, "<div>This divides the whole bill by the rate without subtracting the $25 base fee first.</div>"),
         ]),
    dict(id="B22", domain="Mixed Application", skill="Markup as a percent", difficulty="B",
         strategy="Divide the dollar increase by the original (cost) price",
         misconception="Uses the selling price as the base instead of the cost", error_type="Comprehension",
         question="<p>A store buys a lamp for $40 and sells it for $54. What is the markup as a percent of the cost?</p>",
         answers=[
             ("<div>14%</div>", False, "<div>This treats the $14 difference itself as the percent. Try: divide the change by the original cost.</div>"),
             ("<div>26%</div>", False, "<div>This divides by the selling price ($54) instead of the cost ($40).</div>"),
             ("<div>35%</div>", True, "<div>Increase = $14. 14 &divide; 40 = 0.35 = 35%.</div>"),
             ("<div>135%</div>", False, "<div>This finds the selling price as a percent of the cost but forgets to subtract the original 100%.</div>"),
         ]),
    dict(id="B23", domain="Mixed Application", skill="Multi-step reverse reasoning", difficulty="C",
         strategy="Work backward from the known final value, undoing each step in reverse order",
         misconception="Undoes only one of the two described changes", error_type="Strategy",
         question="<p>A store's sales tripled from Monday to Tuesday, then dropped by half from Tuesday to Wednesday. If Wednesday's sales were $90, what were Monday's sales?</p>",
         answers=[
             ("<div>$30</div>", False, "<div>This only undoes the tripling step. Try: first undo the drop-by-half to find Tuesday, then undo the tripling.</div>"),
             ("<div>$60</div>", True, "<div>Wednesday = Tuesday &divide; 2, so Tuesday = $180. Tuesday = 3 &times; Monday, so Monday = $60.</div>"),
             ("<div>$180</div>", False, "<div>This finds Tuesday's sales but stops before undoing the tripling to reach Monday.</div>"),
             ("<div>$270</div>", False, "<div>This triples Wednesday's sales directly, skipping the halving step entirely.</div>"),
         ]),
    dict(id="B24", domain="Mixed Application", skill="Estimation strategy", difficulty="A",
         strategy="Round each factor to the nearest ten before multiplying",
         misconception="Computes the exact product instead of using the estimation strategy asked for", error_type="Comprehension",
         question="<p>A student estimates 19 &times; 21 by rounding both numbers to the nearest ten. What is the estimate?</p>",
         answers=[
             ("<div>200</div>", False, "<div>Check the rounding: 19 rounds to 20, not 10.</div>"),
             ("<div>399</div>", False, "<div>This is the exact product, not the rounded estimate the question asked for.</div>"),
             ("<div>400</div>", True, "<div>19 rounds to 20 and 21 rounds to 20. 20 &times; 20 = 400.</div>"),
             ("<div>1,600</div>", False, "<div>This rounds to the nearest hundred instead of the nearest ten.</div>"),
         ]),
]

# Representative subset for the confidence-rating reflection (5-6 items, spanning
# domains/difficulty per lesson-1-plan section 27).
CONFIDENCE_IDS = ["B01", "B09", "B13", "B18", "B20", "B23"]
